name: "Deploy safe settings app"
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy new image
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Azure using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.DEPLOY_APP_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_AD_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to Azure Container Registry
        run: az acr login --name hsoghacr

      - name: Build docker image
        run: docker build -t hsoghacr.azurecr.io/safesettings:latest .

      - name: Push image
        run: docker push hsoghacr.azurecr.io/safesettings:latest

      - name: Restart app to load the new image
        run: az webapp restart -n hso-gh-config-app -g hso-gh-config
